---

stages:
  - build
  - deploy

build:
  stage: build
  except:
    - tags
  image:
    name: frankhjung/haskell:9.4.8
  script:
    - touch -d "2023-11-22T04:27:27UTC" LICENSE
    - make setup build doc test
    - mv dist-newstyle/build/x86_64-linux/ghc-9.4.8/Examples-*/doc/html/Examples/ public
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_NAME}
    paths:
      - dist-newstyle/

pages:
  stage: deploy
  dependencies:
    - build
  image: alpine:latest
  script:
    - echo Publishing pages ...
  artifacts:
    paths:
      - public
  only:
    refs:
      - main
